name: Deploy CMS
on:
  push:
    branches:
      - master
    paths:
      - 'cms/**/*'
      - '.github/workflows/cms.workflow.yml'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm --prefix cms ci
      - name: Build
        run: npm run build:cms
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:cms
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'genos-ec52a'
