name: Prod | Update Web
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - partial
env:
  PROJECT: wonkawave
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  TARGET: web
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: web
        run: npm ci
      - name: Configure Release
        id: config
        working-directory: web
        run: echo ::set-output name=VERSION::$(node configure-release.cjs start ${{ inputs.type }} ${{ inputs.release }})
      - name: Build
        if: contains(github.ref, 'build')
        working-directory: web
        run: |
          echo $SV > key.json
          npm run build:prod
        env:
          SV: ${{ env.SERVICE_ACCOUNT }}
      - name: Deploy
        if: contains(github.ref, 'build')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ env.SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.PROJECT }}
          target: ${{ env.TARGET }}
      - name: Update Firestore
        if: contains(github.ref, 'build')
        working-directory: web
        run: node configure-release.cjs finish ${{ steps.config.outputs.VERSION }}
